/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as AuthSsoCallbackIndexImport } from './routes/auth/sso-callback/index'
import { Route as AuthAuthPageIndexImport } from './routes/auth/auth-page/index'
import { Route as LayoutImagesIndexImport } from './routes/_layout/images/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthSsoCallbackIndexRoute = AuthSsoCallbackIndexImport.update({
  id: '/auth/sso-callback/',
  path: '/auth/sso-callback/',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthPageIndexRoute = AuthAuthPageIndexImport.update({
  id: '/auth/auth-page/',
  path: '/auth/auth-page/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutImagesIndexRoute = LayoutImagesIndexImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/images/': {
      id: '/_layout/images/'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof LayoutImagesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/auth/auth-page/': {
      id: '/auth/auth-page/'
      path: '/auth/auth-page'
      fullPath: '/auth/auth-page'
      preLoaderRoute: typeof AuthAuthPageIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sso-callback/': {
      id: '/auth/sso-callback/'
      path: '/auth/sso-callback'
      fullPath: '/auth/sso-callback'
      preLoaderRoute: typeof AuthSsoCallbackIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutImagesIndexRoute: typeof LayoutImagesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutImagesIndexRoute: LayoutImagesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/images': typeof LayoutImagesIndexRoute
  '/auth/auth-page': typeof AuthAuthPageIndexRoute
  '/auth/sso-callback': typeof AuthSsoCallbackIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/images': typeof LayoutImagesIndexRoute
  '/auth/auth-page': typeof AuthAuthPageIndexRoute
  '/auth/sso-callback': typeof AuthSsoCallbackIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/images/': typeof LayoutImagesIndexRoute
  '/auth/auth-page/': typeof AuthAuthPageIndexRoute
  '/auth/sso-callback/': typeof AuthSsoCallbackIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/images' | '/auth/auth-page' | '/auth/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/images' | '/auth/auth-page' | '/auth/sso-callback'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/images/'
    | '/auth/auth-page/'
    | '/auth/sso-callback/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthAuthPageIndexRoute: typeof AuthAuthPageIndexRoute
  AuthSsoCallbackIndexRoute: typeof AuthSsoCallbackIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthAuthPageIndexRoute: AuthAuthPageIndexRoute,
  AuthSsoCallbackIndexRoute: AuthSsoCallbackIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/auth/auth-page/",
        "/auth/sso-callback/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/images/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/images/": {
      "filePath": "_layout/images/index.tsx",
      "parent": "/_layout"
    },
    "/auth/auth-page/": {
      "filePath": "auth/auth-page/index.tsx"
    },
    "/auth/sso-callback/": {
      "filePath": "auth/sso-callback/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
